<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>review</string>
	</array>
	<key>name</key>
	<string>Review Myself</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>review.todo.index</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>review.todo.filepath</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>review.todo.linenum</string>
				</dict>
			</dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>^(\d+\.)\s+(.+)(:\d+)</string>
			<key>name</key>
			<string>review.todo.location</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=\&gt;\s*(p1\.\s*.+)$</string>
			<key>name</key>
			<string>review.todo.todo.p1</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=\&gt;\s*(p2\.\s*.+)$</string>
			<key>name</key>
			<string>review.todo.todo.p2</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\=\&gt;\s*(p3\.\s*.+)$</string>
			<key>name</key>
			<string>review.todo.todo.p3</string>
		</dict>
		<dict>
			<key>comment</key>
			<string></string>
			<key>match</key>
			<string>^#.*</string>
			<key>name</key>
			<string>review.comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.review</string>
	<key>uuid</key>
	<string>2c40f3da-7149-4b92-8c5c-26dfa88b5084</string>
</dict>
</plist>
